### PR TITLE
Update and rename simdjsone.app.src to simdjson.app.src

### PR DESCRIPTION
**Pull request by Zabrane**
Make simdjsone works when building Erlang releases

### CODE REVIEW

**Review by saleyn — APPROVED** [review]

**Comment by saleyn** [comment]
Unfortunately have to revert the change - hex.pm already has sombody else's [simdjson](https://hex.pm/packages/simdjson) project, so I cannot push to hex with this change.

**Comment by Zabrane** [comment]
I was looking for more consistency for file naming. But it's fine @saleyn

**Comment by saleyn** [comment]
Unfortunately, this was the reason for the initial inconsistency, as at the time I created the project, I ran into the naming clash at `hex.pm`.  The other way around it would be to rename the `simdjson.erl` to `simdjsone.erl`, which I am not too opposed of doing.

**Comment by Zabrane** [comment]
> Unfortunately, this was the reason for the initial inconsistency, as at the time I created the project, I ran into the naming clash at `hex.pm`. The other way around it would be to rename the `simdjson.erl` to `simdjsone.erl`, which I am not too opposed of doing.

I think we can live with it like this.
Thanks for at least considering this.

**Pull request merged**
